options:
  source:
    default: ""
    type: string
    description: >
        Space-separated list of NTP servers to use as sources for time.
  peers:
    default: ""
    type: string
    description: >
        Space-separated list of NTP servers to use as peers for time.
        Peers are allowed to query the local NTP server via ntpq.
  pools:
    default: >
        0.ubuntu.pool.ntp.org
        1.ubuntu.pool.ntp.org
        2.ubuntu.pool.ntp.org
        3.ubuntu.pool.ntp.org
        ntp.ubuntu.com
    type: string
    description: >
        Space-separated list of NTP servers to use as pool sources for
        time.  Pool sources are recommended over normal sources for their
        self-healing capabilities. Leave empty to disable pool sources.
  orphan_stratum:
    default: 6
    type: int
    description: >
        The NTP stratum at which ntp most lose connectivity to before it 
        considers itself orphaned, and starts communicating with local peers.
        The default value of 6 will enable orphaned operation when there are
        no stratum 6 servers or servers of a higher stratum available, which
        is two strata below most Internet NTP hosts.
        Set to 0 to disable orphan mode entirely.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe-external-master subordinate charm.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: >
        A comma-separated list of nagios servicegroups.
        If left empty, the nagios_context will be used as the servicegroup.
  nagios_ntpmon_checks:
    default: "offset peers reachability sync"
    type: string
    description: >
        A space-separated list of nagios ntpmon checks to enable.
        Options are "offset peers reachability sync"; if all are specified,
        they are combined into a single check; leave empty for no checks.
  auto_peers:
    default: false
    type: boolean
    description: >
        Automatically select the most appropriate units in the service to
        be a service stratum connecting with upstream NTP servers, and use
        those units as time sources for the remaining units.
  auto_peers_upstream:
    default: 6
    type: int
    description: >
        How many units should attempt to connect with upstream NTP servers?
  use_iburst:
    default: true
    type: boolean
    description: >
        Use iburst for all peers/sources, not just those received via the
        master relation.
