options:
  source:
    default: ""
    type: string
    description: Space separated list of NTP servers to use as source for time.
  peers:
    default: ""
    type: string
    description: Space separated list of NTP servers to use as peers for time.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe-external-master subordinate charm.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
        A comma-separated list of nagios servicegroups.
        If left empty, the nagios_context will be used as the servicegroup.
  nagios_ntpmon_checks:
    default: "offset peers reachability sync"
    type: string
    description: |
        A space-separated list of nagios ntpmon checks to enable.
        Options are "offset peers reachability sync"; if all are specified,
        they are combined into a single check; leave empty for no checks.
  auto_peers:
    default: false
    type: boolean
    description:
        Automatically peer with other units in the same service.
        DEPRECATED.  Please consider using the ntpmaster charm to provide
        sufficient peers for your environment in favour of auto_peers.
  use_iburst:
    default: true
    type: boolean
    description: Use iburst for all servers, not just ntpmaster.
