#!/bin/bash

set -e

source=`config-get source`

if [ -n "$source" ]
then
    cat > /etc/ntp.conf << EOF
# juju generate ntp configuration
driftfile /var/lib/ntp/ntp.drift
statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable
restrict -4 default kod notrap nomodify nopeer noquery
restrict -6 default kod notrap nomodify nopeer noquery
restrict 127.0.0.1
restrict ::1
EOF
    for host in $source
    do
        echo "server $host" >> /etc/ntp.conf
    done
else
    # Restore backup of installed file
    cp /etc/ntp.conf.orig /etc/ntp.conf
fi

service ntp restart || true

